
import Header from '../Header/Header'
import Head from 'next/head'
import Footer from '../Footer/Footer';
import ViewportProvider from './../Resize/Resize';

const Layout = ({ children }) => {

    return (
        <ViewportProvider>
            <Head>
                <title>AB Academy</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="icon" type="image/ico" href="/img/goals.ico" />
            </Head>
            <Header />
            <main>{ children }</main>
            <Footer />
        </ViewportProvider>

    )
}

export default Layout;




